### ISSUE TITLE
Add bin/exec_env to customize environment.

### ISSUE THREAD

**Issue by vic** [jthegedus/asdf-gcloud#13]
Should we have a [`bin/exec_env`](https://asdf-vm.com/#/plugins-create?id=binexec-env) file that exports `CLOUDSDK_PYTHON` automatically, instead of requiring the following to be executed by the user?

```bash
python_sdk="$(command -v python)"
export CLOUDSDK_PYTHON="${python_sdk}"
```

**Comment by jthegedus** [comment]
Yep, working on that now 😄

**Comment by jthegedus** [comment]
@vic Please give that implementation a look 😃
