### ISSUE TITLE
asdf list-all command returning incorrect version numbers

### ISSUE THREAD

**Issue by rafaelgalani** [jthegedus/asdf-gcloud#27]
**Describe the bug**
Some versions in `asdf list-all` command are not being returned properly, such as `207.0.0`, `208.0.0`, and the latest one (`325.0.0`).
Apparently, looks like the versions are being joined on the same line.

**Steps to reproduce**
With a clean installation of `asdf` (or one with the `gcloud` plugin recently installed), run the default installation steps:
- `asdf plugin add gcloud https://github.com/jthegedus/asdf-gcloud.git`;
- `asdf install gcloud latest` or `asdf list-all`.

If you ran `asdf install gcloud latest`, like I did, the installation will fail. 
That is because the script is looking for an unexistent file (version `324.0.0325.0.0`). This seems to be happening with only two versions, as mentioned above.

**Expected behavior**

`asdf list-all` must return the correct version numbers.

**Screenshots**
![zsh_output.png](https://i.imgur.com/TYnHpMY.png)

**Comment by rafaelgalani** [comment]
I'll work on it. I'm just filling out the issue to make sure it's documented 😸

**Comment by jthegedus** [comment]
Thanks for the thorough documentation of the bug :100:

**Comment by jthegedus** [comment]
And for providing a solution :tada: I appreciate this a lot, thanks again!
