### ISSUE TITLE
google-cloud-sdk releases lagging behind upstream by one version

### ISSUE THREAD

**Issue by itspngu** [jthegedus/asdf-gcloud#40]
**Is your feature request related to a problem? Please describe.**

Currently (and I'm suspecting in the past, too) the [latest release](https://cloud.google.com/sdk/docs/release-notes#33500_2021-04-06) of the SDK is missing from `asdf list-all gcloud`. Looking at what happens in `/bin/list-all` and [following through](https://storage.googleapis.com/storage/v1/b/cloud-sdk-release/o?pageToken=Cihnb29nbGUtY2xvdWQtc2RrLTMyNC4wLjAtd2luZG93cy14ODYuemlw&prefix=google-cloud-sdk&fields=kind,nextPageToken,items(name)) to the GCS bucket which release info is parsed from, that makes sense, as currently `335.0.0` is missing. The latest version `asdf-gcloud` offers is `334.0.0`, which is in line with the bucket's contents.

**Describe the solution you'd like**

I'd like to be able to install the latest release of the SDK. Off the top of my head there's a few options to facilitate that:

- Ask the maintainers of the SDK to include new releases in the archives on release, rather than having a location split between archive and latest - I'm suspecting there's a reason they don't already do that
- Assume that the bucket is lagging behind by one version and account for that in `/bin/list-all` - this is pretty dirty, even if one was to add something along the lines of `curl -X HEAD https://...one_version_higher.tar.gz`, as it might break in the future
- Look for an alternate location of releases - I haven't been able to find the SDK on their Github except for the [containerized variant](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/releases) of it

**Describe alternatives you've considered**

See above.

**Additional context**

Depending on the proposed solution I'm able to help with implementing this.

**Comment by jthegedus** [comment]
The GCS bucket contents align with the release notes for the [Cloud SDK here](https://cloud.google.com/sdk/docs/release-notes). I have seen some delay, but that has always been less than 24hrs before they all align and seems acceptable unless something is done upstream.

Given https://github.com/asdf-vm/asdf-plugins/pull/397 and the fact there's no real alternative solution here, I will close.

Thanks for raising.
