### ISSUE TITLE
bug: unbound variable when `gcloud` run without args

### ISSUE THREAD

**Issue by ckchow** [jthegedus/asdf-gcloud#68]
### Describe the bug

❯ gcloud
/opt/homebrew/opt/asdf/libexec/lib/commands/command-exec.bash: line 23: shim_args[@]: unbound variable

### Steps to reproduce

1. asdf plugin-add gcloud
2. asdf global gcloud latest
3. gcloud

### asdf version

0.10.2

### asdf-gcloud version

1.2.1

### gcloud version

403.0.0

### Additional Information

I think it might be the same kind of cause as https://github.com/asdf-vm/asdf/issues/522

**Comment by ckchow** [comment]
The issue I mentioned actually links to [this](https://github.com/code-lever/asdf-rust/issues/17).

**Comment by ckchow** [comment]
Just noticed the bit in the readme about this, my bad!

**Comment by 2Judy2** [comment]
This is really a bug. 
Had to remove the `set -u` from `~/.asdf/plugins/gcloud/lib/utils.bash` 

For anyone in the future to get it working alter `set -euo pipefail` (line 3) to `set -eo pipefail` in mentioned file.
