### ISSUE TITLE
bug:  Won't upgrade past version 403

### ISSUE THREAD

**Issue by Cartman75** [jthegedus/asdf-gcloud#70]
### Describe the bug

For some reason, it won't upgrade past 403. When I look at the google gcs bucket, its up to 407. (current as of now)

### Steps to reproduce

asdf list all gcloud

### asdf version

v0.10.2-7e7a1fa

### asdf-gcloud version

?

### gcloud version

403.0.0

**Comment by jthegedus** [comment]
It appears the pagination code has a bug for the `list all` function.

You can still install the versions even though they are not listed. `asdf install gcloud 408.0.0` still works.

**Comment by Cartman75** [comment]
Ah ok, I can deal with that then. Thanks!

**Comment by sbocinec** [comment]
I'm affected by the same issue and proposed a fix in #72 as there is only a minor issue with the regular expression used in the `list-all` script - missing `=` character.

**Comment by jthegedus** [comment]
Released in https://github.com/jthegedus/asdf-gcloud/releases/tag/v1.2.2

Thanks @sbocinec
