### ISSUE TITLE
bug: Using gcloud without any parameters will crash

### ISSUE THREAD

**Issue by onnimonni** [jthegedus/asdf-gcloud#73]
### Describe the bug

I have a fresh installation of MacOS and asdf on a Macbook where I have ran following:
```
# On MacOS 13.1 (22C65)
$ brew install asdf
$ asdf plugin add gcloud
$ asdf plugin add python
$ asdf install python 3.11.1
$ asdf install gcloud 415.0.0
```

I'm using fish shell with these lines in my `~/.config/fish/config.fish`:
```fish
# Use asdf installed with homebrew
if type -q brew
  if type -q asdf
    source (brew --prefix asdf)/libexec/asdf.fish
  end
end

# Add fish completions from homebrew
if test -d /opt/homebrew/share/fish/vendor_completions.d
    source /opt/homebrew/share/fish/vendor_completions.d/*.fish
end
if test -d /opt/homebrew/share/fish/vendor_functions.d
    source /opt/homebrew/share/fish/vendor_functions.d/*.fish
end
```

When I run just bare `gcloud` I get following error:
```bash
$ gcloud
/opt/homebrew/opt/asdf/libexec/lib/commands/command-exec.bash: line 23: shim_args[@]: unbound variable
```

I would have expected to get list of all gcloud commands instead.

When I run command with parameters eg:
```
$ gcloud auth login
```
It works just fine.

I'm not sure if this is failure on my configuration but seems that something is wrong with the `/opt/homebrew/opt/asdf/libexec/lib/commands/command-exec.bash`

For example if I run `python` installed with asdf I don't get any problems:
```bash
$ which python
~/.asdf/shims/python
$ python
Python 3.11.1 (main, Jan 27 2023, 08:09:37) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

### Steps to reproduce

```
$ asdf gcloud --version
Unknown command: `asdf gcloud --version`
No documentation for plugin gcloud
```

### asdf version

v0.11.1

### asdf-gcloud version

v1.2.2

### gcloud version

415.0.0

**Comment by onnimonni** [comment]
Same thing also happens with `kubectl` installed through `gcloud`
```bash
$ kubectl
/opt/homebrew/opt/asdf/libexec/lib/commands/command-exec.bash: line 23: shim_args[@]: unbound variable
```

**Comment by cathex-matt** [comment]
I think the above behavior is explained here https://github.com/jthegedus/asdf-gcloud#faq

**Comment by jtama** [comment]
Actually this IS a bug as it prevents using gke-gcloud-auth-plugin... which forces me to rollback

**Comment by sodabrew** [comment]
This errors prevents using gke-gcloud-auth-plugin. I removed the `u` from the line `set -euo pipefail` in `.asdf/plugins/gcloud/lib/utils.bash` in order to update my asdf gcloud plugin to the latest release and connect to my GKE cluster.

What would a proper fix look like that both handles no arguments and errors out on other unset variables, e.g. to catch typos during dev work?

**Comment by jtama** [comment]
Actually sourcing the plugins as printed at install time did solve the issuer for me : 

source /Users/<user>/.asdf/installs/gcloud/431.0.0/completion.zsh.inc
source /Users/<user>/.asdf/installs/gcloud/431.0.0/path.zsh.inc

Must have misses configured before.
